package com.cq.sandbox;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
public class CqojCodeSandboxApplication {

    public static void main(String[] args) {
        SpringApplication.run(CqojCodeSandboxApplication.class, args);
    }

}
